# action.yml
name: 'Assign to One Project'
description: 'Assign new/labeled Issue or Pull Request to a specific project dashboard column'
author: sahandilshan
inputs:
  # project:
  #   description: 'The url of the project to be assigned to.'
  #   required: true
  # column_name:
  #   description: 'The column name of the project, defaults to "To do" for issues and "In progress" for pull requests.'
  #   required: false
  project:
    description: 'Project id'
    required: true
  column_name:
    description: 'Column name'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project }}
    - ${{ inputs.column_name }}

branding:
  icon: 'box'
  color: 'red'
